language: java
jdk:
  - oraclejdk8

install:
  ## https://docs.travis-ci.com/user/migrating-from-legacy/#Adding-APT-Sources
   #   - echo "deb https://<my.favorite.cran.mirror>/bin/linux/ubuntu precise/" | sudo tee -a /etc/apt/sources.list
#  - sudo apt-get install -y r-base
#  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && sudo apt-get update && sudo apt-get install -y r-base
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - sudo sh -c 'gpg -a --export E084DAB9 | sudo apt-key add -'
  - sudo apt-get update
  - sudo apt-get install -y r-base

  - sudo chmod -R ugo+w /usr/local/lib/R/site-library

  ## install packages needed for testing
  - R -e 'chooseCRANmirror(graphics=FALSE, ind=10); install.packages("devtools")'
  - R -e 'devtools::source_url("https://raw.githubusercontent.com/holgerbrandl/datautils/v1.38/R/core_commons.R"); load_pack(R.utils); load_pack(lubridate); load_pack(caret); load_pack(tidyverse); load_pack(mvtnorm);'







