language: java
jdk:
  - oraclejdk8

install:
  ## https://docs.travis-ci.com/user/migrating-from-legacy/#Adding-APT-Sources
   #   - echo "deb https://<my.favorite.cran.mirror>/bin/linux/ubuntu precise/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get install -y r-base
  - sudo chmod -R ugo+w /usr/local/lib/R/site-library

  ## install packages needed for testing
  - R -e 'chooseCRANmirror(graphics=FALSE, ind=10); install.packages("devtools")'
  - R -e 'devtools::source_url("https://raw.githubusercontent.com/holgerbrandl/datautils/v1.38/R/core_commons.R"); load_pack(R.utils); load_pack(lubridate); load_pack(caret); load_pack(tidyverse)'







